[package]
name = "anon-sym-ake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lb-vrf = { git = "https://github.com/jiep/lb-vrf" }
rand = "0.8.5"
hex = "0.4.3"
oqs = "0.7.2"
#sha3 = "0.10.6"
#aes-gcm = "0.10.1"