on: [push]

name: rust

jobs:
  build_and_test:
    name: Build binary, test, and check format
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-20.04,
              target: "x86_64-unknown-linux-gnu"
            }
          - {
              os: windows-latest,
              target: "x86_64-pc-windows-msvc"
            }
          - {
              os: macos-latest,
              target: "x86_64-apple-darwin"
            }
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}
      
      - name: Check code
        run: cargo check

      - name: Check tests
        run: cargo test
      
      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check Clippy
        run: cargo clippy -- -D warnings

  deploy:
    name: Create binaries ${{ matrix.config.target }}
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: ubuntu-latest,
              target: "x86_64-unknown-linux-gnu"
            }
          - {
              os: windows-latest,
              target: "x86_64-pc-windows-msvc"
            }
          - {
              os: macos-latest,
              target: "x86_64-apple-darwin"
            }
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install cargo-strip
        run: cargo install --force cargo-strip

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}

      - name: Build target
        run: |
          cargo build --release --target ${{ matrix.config.target }}
          cargo strip

      - name: Package all targets
        shell: bash
        if: ${{ !contains(matrix.config.target, 'windows') }}
        run: |
          BIN=generic-anon-ake
          TARGET=${{ matrix.config.target }}
          if [[ ${TARGET} == *"darwin"* ]]; then
            brew install coreutils
          fi
          cd target/${TARGET}/release
          if [[ ${TARGET} != *"windows"* ]]; then
            sha256sum ${BIN_NAME}* > digest.sha256
          fi
          zip ../../../${BIN}-${TARGET}.zip ${BIN_NAME} digest.sha256
          cd -
      - name: Package all targets for Windows
        if: ${{ contains(matrix.config.target, 'windows') }}
        shell: bash
        run: |
          BIN=generic-anon-ake
          BIN_NAME=${BIN}.exe
          TARGET=${{ matrix.config.target }}
          cd target/${TARGET}/release
          sha256sum ${BIN_NAME}* > digest.sha256
          tar.exe acvf ../../../${BIN}-${TARGET}.zip ${BIN_NAME} digest.sha256
          cd -
      - name: Add to Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  benchmark: 
    name: Run benchmark
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Check machine info
        run: lscpu

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run benchmark
        run: cargo bench

      - name: Set Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate graphics
        run: |
          pip install -r graphics/requirements.txt
          python graphics/generate_graphics.py
        
      - name: Package results
        shell: bash
        run: |
          zip -r benchmark-linux.zip target/criterion/*

      - name: Add to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}