on: [push]

name: rust

jobs:
  build_and_test:
    name: Build binary, test, and check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Check code
        run: cargo check

      - name: Check tests
        run: cargo test
      
      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check Clippy
        run: cargo clippy -- -D warnings

  deploy:
    name: Create binaries ${{ matrix.config.target }}
    needs: build_and_test
    #if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.config.os }}
    strategy: 
      matrix:
        config:
          - {
              os: ubuntu-latest,
              target: "x86_64-unknown-linux-gnu"
            }
          - {
              os: windows-latest,
              target: "x86_64-pc-windows-gnu"
            }
          - {
              os: macos-latest,
              target: "x86_64-apple-darwin"
            }
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.config.target }}

      - name: Package all targets
        shell: bash
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          BIN=anon-sym-ake
          BIN_NAME=$BIN
          TARGET=${{ matrix.config.target }}
          if [[ ${TARGET} == *"windows"* ]]; then
            BIN_NAME=${BIN}.exe
          fi
          strip target/release/${BIN_NAME}
          cd target/release
          sha256sum ${BIN_NAME} | cut -f 1 -d " " > digest.sha256
          zip ../../${BIN}-${TARGET}.zip ${BIN_NAME} digest.sha256
          cd -
      - name: Add to Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

  benchmark: 
    name: Run benchmark
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cargo install cargo-criterion
          cargo install criterion-table

      - name: Run benchmark
        run: | 
          cargo criterion --message-format=json | criterion-table > BENCHMARKS.md
          mv BENCHMARKS.md target/criterion/

      - name: Package results
        shell: bash
        run: |
          BIN=anon-sym-ake
          zip -r benchmark-linux.zip target/criterion/*

      - name: Add to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}